lab6ppw/urls.py
from django.contrib import admin
from django.urls import path,include
from tdd.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tdd.urls')),
    path('',include('django.contrib.auth.urls')),
]

tdd/urls.py
from django.urls import include, path
from . import views
from django.shortcuts import render
from django.conf.urls import url

app_name = 'tdd'
urlpatterns = [
	path('status/',views.home,name='index'),
	path('books/',views.search_books,name='books'),
	path('',views.main,name='main'),
	path('landing/',views.landing,name='landing'),
]

tdd/models.py
from django.db import models

class modelStatus(models.Model):
	status = models.TextField(max_length=300)
	time = models.DateTimeField(auto_now=True)

tdd/forms.py
from django import forms
from . import models

class formStatus(forms.Form):
	status = forms.CharField(max_length=300,required =True)
	# time = forms.DateTimeField(initial= datetime.now())

tdd/views.py
from django.shortcuts import render, redirect
from .models import modelStatus
from .forms import formStatus

def home(request):
	status = modelStatus.objects.all()
	createStatus = formStatus(request.POST or None)
	context={
		'stats':status,
		'form_status':createStatus,
	}

	if request.method=='POST':
		if createStatus.is_valid():
			status.create(
				status = createStatus.cleaned_data.get('status'),
				time = createStatus.cleaned_data.get('time'),
				)
	return render(request,'status.html',context)
def main(request):
	return render(request,'main.html',{})
def search_books(request):
	return render(request,'search-books.html',{})
def landing(request):
	return render(request,'registration/landing.html',{})
# Create your views here.

tdd/templates/base.html
{% load static %}
<head>
	<title>Meldi's</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
	<script src="{% static 'js/main.js' %}"></script>
</head>

tdd/templates/main.html
{% load static %}
<!DOCTYPE html>
<html>
{% include "base.html" %}
<body id = "body">
{% include "navbar.html" %}
<br>
<div style="padding-top: 60px;" class="text-center">
	<img class="circular-image" src="https://i.ibb.co/T04Hvxk/IMG-1353-min.jpg">
	<h1>Meldi Hafizh S</h1>
</div>


<div class="mx-auto text-center" style="width: 50%;">
	<dl class="accordion">
		<dt><a href="">Aktivitas</a></dt>
		<ul class="list-group">
			<li class="list-group-item py-2">Kuliah</li>
			<li class="list-group-item py-2">Organisasi</li>
		</ul>

		<dt><a href="">Experiences</a></dt>
		<ul class="list-group">
			<li class="list-group-item">Teaching Assistant for DDP-1</li>
			<li class="list-group-item">Head of Social Service Department at FUKI Fasilkom UI</li>
			<li class="list-group-item">Staff of Social Service Department at BEM Fasilkom UI</li>
		</ul>

		<dt><a href="">Prestasi</a></dt>
		<ul class="list-group">
			<li class="list-group-item">Null.</li>
		</ul>
	</dl>
</div>


</body>
</html>

tdd/templates/navbar.html
{% if user.is_authenticated %}
<nav class="navbar navbar-expand navbar-dark bg-dark d-flex justify-content-end fixed-top">
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav d-flex mr-auto">
      <a class="nav-item nav-link active" href="{% url 'tdd:main' %}">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="{% url 'tdd:index' %}">Status</a>
      <a class="nav-item nav-link active" href="{% url 'tdd:books' %}">Cari Buku</a>
    </div>
    <ul class="navbar-nav ml-auto">
        <button class="btn text-light" onclick="grayScaleTheme()">Toggle Grayscale</button>
        <a class="nav-item nav-link active" href="{% url 'logout' %}">Logout</a>
    </ul>
  </div>
</nav>
{% else %}
      <nav class="navbar navbar-expand navbar-dark bg-dark d-flex justify-content-end fixed-top">
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav d-flex mr-auto">
      <a class="nav-item nav-link active" href="{% url 'tdd:main' %}">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="{% url 'tdd:index' %}">Status</a>
      <a class="nav-item nav-link active" href="{% url 'tdd:books' %}">Cari Buku</a>
    </div>
    <ul class="navbar-nav ml-auto">
        <button class="btn text-light" onclick="grayScaleTheme()">Toggle Grayscale</button>
        <a class="nav-item nav-link active" href="{% url 'login' %}">Login</a>
      </ul>
  </div>
</nav>
{% endif %}

tdd/templates/search-books.html
{% load static %}
<!DOCTYPE html>
<html>
{% include "base.html" %}
<body id = "body">
{% include "navbar.html" %}
<br>
<div class="containter" style="padding-top: 60px;">
	<h1>Search Books</h1>
	<div>
		<input type="text" id="search" placeholder="Input the books name" class="form-control"> <button type="Submit" id="submit">Search</button>

	<table class="table table-dark table-striped">
  		<thead>
    		<tr>
     			<th scope="col">Nama Buku</th>
      			<th scope="col">Penulis Buku</th>
      			<th scope="col">Gambar Buku</th>
    		</tr>
    	</thead>
 		<tbody id="result">
  
  		</tbody>
	</div>
</div>
</body>
</html>

tdd/templates/status.html
{% load static %}
<!DOCTYPE html>
<html>
{% include "base.html" %}
<body>
{% include "navbar.html" %}
<br>
<div style="padding-top: 56px;">Halo, Apa kabar?</div>
<form method="POST">
	{% csrf_token %}
	<p>
		{{form_status.as_p}}
	</p>
	<button type="Submit" name="submit">Submit</button>
</form>
	<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">Tanggal & Waktu</th>
      <th scope="col">Status</th>
    </tr>
    </thead>
 <tbody>
  	{% for stat in stats %}
    <tr>
      <th scope="row">{{stat.time}}</th>
      <td>{{stat.status}}</td>
    </tr>
    {% endfor %}
  </tbody>
</body>
</html>